# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]

prepend_keymap = [
	{ on   = "!", for  = "windows", run  = 'shell "cmd.exe" --block', desc = "Open CMD here" },
	{ on   = "!", for  = "unix", run  = 'shell "$SHELL" --block', desc = "Open $SHELL here" },
	{ on = "<A-Esc>", run = "quit", desc = "Quit the process" },
#	{ on = ["<Esc>", "<Esc>"], run = "quit", desc = "Quit the process" },
]
